const MAX_NAME=80,MAX_EMAIL=160,MAX_TEXT=2000;
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function clean(v,max){return typeof v==="string"?v.trim().replace(/[<>]/g,"").slice(0,max):""}
function validOrigin(r){return r.headers.get("Origin")==="https://devahmad-blog.pages.dev"}
function normalizeForModeration(v){return String(v||"").toLowerCase().normalize("NFKC").replace(/[أإآٱ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/ؤ/g,"و").replace(/ئ/g,"ي").replace(/ـ/g,"").replace(/[0]/g,"o").replace(/[1!|]/g,"i").replace(/[3]/g,"e").replace(/[4@]/g,"a").replace(/[5$]/g,"s").replace(/[7]/g,"t").replace(/[^a-z\u0600-\u06ff]+/g,"").replace(/(.)\1{2,}/g,"$1$1")}
const BAD=["fuck","fuk","fck","fucker","fucking","shit","bitch","asshole","dick","pussy","cunt","motherfucker","كس","كسم","كسامك","كسامو","كسخت","شرموط","شرموطه","شراميط","قحبه","قحبه","منيوك","منيوكه","طيز","زب","زبي","زبر","خول","عرص","نيك","انيك","لعين","يلعن","يلعنابوك","يلعنامك"];
function hasAbuse(v){const n=normalizeForModeration(v);return BAD.some(w=>n.includes(normalizeForModeration(w)))}
function looksSpam(v){const links=(String(v).match(/(?:https?:\/\/|www\.|\b[a-z0-9-]+\.(?:com|net|org|io|xyz|top|click|shop)\b)/gi)||[]).length;const repeats=/(.{4,})\1{2,}/i.test(String(v));return links>1||repeats}
function moderationStatus(name,content){return hasAbuse(name)||hasAbuse(content)||looksSpam(content)?"rejected":"approved"}
export async function onRequest({request,env}){try{if(request.method==="GET"){const page=new URL(request.url).searchParams.get("page");if(!page)return json({error:"missing page"},400);const {results}=await env.COMMENTS_DB.prepare("SELECT id,name,content,created_at FROM comments WHERE page_id=? AND status='approved' ORDER BY created_at DESC").bind(page).all();return json({comments:results})}if(request.method==="POST"){if(!validOrigin(request))return json({error:"forbidden"},403);let body;try{body=await request.json()}catch{return json({error:"invalid json"},400)}const page=clean(body.page_id,200),title=clean(body.article_title,200),name=clean(body.name,MAX_NAME),email=clean(body.email,MAX_EMAIL),content=clean(body.content,MAX_TEXT);if(!page||!title||!name||!content)return json({error:"required fields"},400);if(content.length<3)return json({error:"comment too short"},400);const status=moderationStatus(name,content);await env.COMMENTS_DB.prepare("INSERT INTO comments(page_id,article_title,name,email,content,status) VALUES(?,?,?,?,?,?)").bind(page,title,name,email,content,status).run();return status==="approved"?json({success:true,message:"تم نشر التعليق"}):json({success:true,message:"تم استلام التعليق"})}return json({error:"method not allowed"},405)}catch(e){return json({error:"server error"},500)}}
